[component]
file = "acos.py"
id = "dd89daaf-f04b-447c-9220-9791ed55fbd5"

[component.details]
name = "acos"
namespace = "Maths"
description = "Computes the inverse cosine function of a value to give an angle in radians."
keywords = [ "arccosine", "trigonometry", "triangle" ]

[component.details.inports]
value = { name = "Value", description = "Value bounded between -1 to 1." }

[component.details.outports]
result = { name = "Result", description = "" }
