[component]
file = "sin.py"
id = "bfce4f5f-8b5f-4a9f-8755-31dca45686b2"

[component.details]
name = "sin"
namespace = "Maths"
description = "Computes the sine of an angle which is equal to the opposite length of a right angled triangle divided by its hypotenuse length."
keywords = [ "sine", "trigonometry", "triangle" ]

[component.details.inports]
angle = { name = "Angle", description = "Angle in radians." }

[component.details.outports]
result = { name = "Result", description = "" }
