[component]
file = "cos.py"
id = "dd89daaf-f04b-447c-9220-9791ed55fbd5"

[component.details]
name = "cos"
namespace = "Maths"
description = "Computes the cosine of an angle which is equal to the adjacent length of a right angled triangle divided by its hypotenuse length."
keywords = [ "cosine", "trigonometry", "triangle" ]

[component.details.inports]
angle = { name = "Angle", description = "Angle in radians." }

[component.details.outports]
result = { name = "Result", description = "" }
