[component]
id          = "dd89daaf-f04b-447c-9220-9791ed55fbd5"
name        = "cos"
namespace   = "Maths"
description = "Computes the cosine of an angle which is equal to the adjacent length of a right angled triangle divided by its hypotenuse length."
keywords    = ["cosine", "trigonometry", "triangle"]

[component.files]
main   = "cos.py"
readme = "README.md"

[component.inports]
angle = { name = "Angle", description = "The angle to compute the cosine of." }

[component.outports]
result = { name = "Result", description = "The result of cosine which will be between -1 to 1." }

[component.settings]
angle_format = { label = "Angle Format" }
