[component]
id = "f0199dde-f344-4b06-a082-296fe3187fe1"
name = "Divide"
namespace = "Maths"
description = "Divides the numerator from the denominator value."
keywords = [ "/", "division", "arithmetic" ]

[component.files]
main = "divide.py"
readme = "README.md"

[component.outports]
result = { name = "Result" }

[component.settings]
terms = { label = "Number of Terms" }
