repos:
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.24.0
    hooks:
      - id: nitpick

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.15.2
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/hakancelik96/unimport
    rev: 0.7.4
    hooks:
      - id: unimport
        args: [--remove, --include-star-import]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort

  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.9.2
    hooks:
      - id: blacken-docs
