repos:
  - repo: https://github.com/hakancelik96/unimport
    rev: v0.2.7
    hooks:
      - id: unimport
        additional_dependencies: [toml]
        args: [-c, pyproject.toml, -r, --include-star-import]

  - repo: https://github.com/asottile/seed-isort-config
    rev: master
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
