[tool.poetry]
name = "pycomponents_general_maths"
description = "A Package of Python Flow Components"
authors = ["Matthew Stedman <matt@theengineeringcompany.com>"]
version = "0.1.0"
license = "MIT"
readme = "README.md"
repository = "https://github.com/theengineeringco/pycomponents_general_maths.git"

[tool.poetry.dependencies]
python = "^3.6.1"
#tec-flow = {git ="https://github.com/theengineeringco/PythonAbstraction.git"}
tec-flow = {path ="C:/Users/matts/Documents/Flow_component_development/flow_types_eng"}
flow_pycomponents_utils = {path = "../flow_pycomponents_utils"}

[tool.poetry.dev-dependencies]
black = "^19.10b0"
wemake-python-styleguide = "^0.14.0"
pytest = "^5.4.1"
taskipy = "^1.2.1"
flow-python-cookiecutter = {git ="https://github.com/theengineeringco/FlowPythonCookiecutter.git"}

[tool.poetry.plugins."flow.components"]
"pycomponents_general_maths" = "tec_flow._tools.find_components:find_pkg_components"

[tool.taskipy.tasks]
create_component = "flow_python_cookiecutter -t component"

[tool.black]
line-length=120

[build-system]
requires = ["poetry>=1.0", "pip>=20.0"]
build-backend = "poetry.masonry.api"
