[component]
file = "factorial.py"
id = "49162650-7299-4a97-a189-260c2ea416ea"

[component.details]
name = "Factorial"
namespace = "Maths"
description = "Computes the product of all positive integers less than or equal to the value provided."
readme = "README.md"
keywords = [ "!" ]

[component.details.inports]
value = { name = "Value", description = "" }

[component.details.outports]
result = { name = "Result", description = "" }
