[component]
file = "min.py"
id = "0e027500-1763-486b-b4fa-f10685368a33"

[component.details]
name = "Min"
namespace = "Maths"
description = "Finds the lowest value."
readme = "README.md"
keywords = [ "minimum", "smallest" ]

[component.details.inports]
Values = { name = "Values", description = "A collection of values." }

[component.details.outports]
result = { name = "Result", description = "" }
