[component]
id          = "a1a3e0ad-a2be-42e9-881c-8d285499392e"
name        = "asin"
namespace   = "Maths"
description = "Computes the inverse sine function of a value to give an angle in radians."
keywords    = ["arcsine", "trigonometry", "triangle"]

[component.files]
main   = "asin.py"
readme = "README.md"

[component.inports]
value = { name = "Value", description = "The value to compute the arccosine of. It must be bounded between -1 to 1." }

[component.outports]
result = { name = "Result", description = "Result of arcsine." }

[component.settings]
angle_format = { label = "Angle Format" }
