[component]
id        = "dab652a2-af9e-494a-ae35-25759357dc0c"
name      = "Power"
namespace = "Maths"
description = "Raises a value to a power."
readme    = "README.md"
keywords  = ["^", "exponetiation"]

[component.files]
main = "power.py"

[component.inports]
value  = { name="Value", description="Value to be raised." }
exponent = { name="Exponent", description="Exponent number." }

[component.outports]
result = { name="Result", description="" }
