[component]
id          = "34170d07-f361-4221-969e-230e68211691"
name        = "Increment"
namespace   = "Maths"
description = "Increases an integer value given an increment value."
keywords    = ["++", "addition", "arithmetic", "plus"]

[component.files]
main   = "increment.py"
readme = "README.md"

[component.inports]
value     = { name = "Value", description = "Value to increment." }
increment = { name = "Increment", description = "The amount to increment by." }

[component.outports]
result = { name = "Result", description = "Result after incrementing." }
