[component]
id          = "315a3b9f-cfdc-4b2d-b76d-e22746239c24"
name        = "Round Down"
namespace   = "Maths"
description = "Always rounds down the value given the specified number of decimal places."
keywords    = ["down"]
deprecation = "This component is deprecated and will be removed in a future release. Please use the newer component Round that enables rounding up, down and nearest using its settings."

[component.files]
main   = "round_down.py"
readme = "README.md"

[component.inports]
value          = { name = "Value", description = "Value to be rounded." }
decimal_places = { name = "Decimal Places", description = "The decimal place to round off on. If not given, the value will be rounded to nearest integer." }

[component.outports]
result = { name = "Result", description = "Result of the round." }
