[component]
id        = "315a3b9f-cfdc-4b2d-b76d-e22746239c24"
name      = "Round Down"
namespace = "Maths"
description = "Always rounds down the value given the specified number of decimal places."
readme    = "README.md"
keywords  = ["nearest"]

[component.files]
main = "round_down.py"

[component.inports]
value        = { name="Value", description="" }
decimal_places = { name="Decimal Places", description="If not given, output will be rounded to nearest integer." }

[component.outports]
result = { name="Result", description="" }
