[component]
id        = "a3938fef-32be-48c3-a5e6-35e32b62bdd1"
name      = "Add"
namespace = "Maths"
description = "Adds two values together."
keywords  = ["+", "addition", "arithmetic", "plus"]

[component.files]
main = "add.py"
readme = "README.md"

[component.outports]
result = { name = "Result" }

[component.settings]
terms = { name = "Number of Terms" }
