[component]
id          = "a3938fef-32be-48c3-a5e6-35e32b62bdd1"
name        = "Add"
namespace   = "Maths"
description = "Adds two values together."
keywords    = ["+", "addition", "arithmetic", "plus"]

[component.files]
main   = "add.py"
readme = "README.md"

[component.settings]
terms = { label = "Number of Terms" }

[component.inports]
value1 = { name = "Value 1", description = "First value to be added." }
value2 = { name = "Value 2", description = "Second value to be added." }

[component.outports]
result = { name = "Result", description = "Result of the addition." }
