[component]
file = "absolute.py"
id = "b297ab4c-8da2-4c6c-b82f-6da84ddcb93a"

[component.details]
name = "Absolute"
namespace = "Maths"
description = "Computes the absolute or the non-negative of a value."
readme = "README.md"
keywords = [ "modulus", "||", "abs", "arithmetic" ]

[component.details.inports]
value = { name = "Value", description = "" }

[component.details.outports]
result = { name = "Result", description = "" }
