[component]
id        = "7038eb76-b98a-4cb4-898e-0d47f4aa8585"
name      = "Absolute"
namespace = "Maths"
description = "Computes the absolute or the non-negative of a value"
keywords  = ["modulus", "||", "abs"]

[component.files]
main = "absolute.py"
readme = "README.md"

[component.inports]
value = { name="Value" }

[component.outports]
result = { name="Result" }
