[component]
id = "c9477619-3ccc-4399-b756-fbc57ea5893a"
name = "Sum"
namespace = "Maths"
description = "Adds a sequence of values together."
keywords = [ "summation", "arithmetic" ]

[component.files]
main = "sum.py"
readme = "README.md"

[component.inports]
values = { name = "Values", description = "A list of values." }

[component.outports]
result = { name = "Result", description = "The summation of the list." }
