[component]
file = "subtract.py"
id = "f5c24b3d-9ca8-43b1-8917-7991d53874a5"

[component.details]
name = "Subtract"
namespace = "Maths"
description = "Subtracts the first value from the second value."
readme = "README.md"
keywords = [ "-", "subtraction", "arithmetic", "minus" ]

[component.details.inports]
value1 = { name = "Value 1", description = "" }
value2 = { name = "Value 2", description = "" }

[component.details.outports]
result = { name = "Result", description = "" }
