[component]
id = "f5c24b3d-9ca8-43b1-8917-7991d53874a5"
name = "Subtract"
namespace = "Maths"
description = "Subtracts the first value from the second value."
keywords = [ "-", "subtraction", "arithmetic", "minus" ]

[component.files]
main = "subtract.py"
readme = "README.md"

[component.outports]
result = { name = "Result" }

[component.settings]
terms = { label = "Number of Terms" }
