[component]
file = "negative.py"
id = "ac1f5353-736e-465e-b7ee-9d3fb7e106ce"

[component.details]
name = "Negative"
namespace = "Maths"
description = "Computes the negative of a value."
keywords = [ "-", "arithmetic" ]

[component.details.inports]
value = { name = "Value", description = "" }

[component.details.outports]
result = { name = "Result", description = "" }
