[component]
id          = "b3674dca-8a1c-4926-880c-ead3f32964f7"
name        = "Negative"
namespace   = "Maths"
description = "Computes the negative of a value"
keywords    = ["-"]

[component.files]
main   = "negative.py"
readme = "README.md"

[component.inports]
value = { name = "Value", description = "Value to take the negative of." }

[component.outports]
result = { name = "Result", description = "Negative of the value." }
