[component]
file = "decrement.py"
id = "1b819eac-d410-43ae-be7c-92d8440ae278"

[component.details]
name = "Decrement"
namespace = "Maths"
description = "Decreases an integer value given an increment value."
readme = "README.md"
keywords = [ "--", "subtraction", "arithmetic", "minus" ]

[component.details.inports]
value = { name = "Value", description = "Value to decrement" }
decrement = { name = "Decrement", description = "The amount to decrement by" }

[component.details.outports]
result = { name = "Result", description = "" }
