[component]
id        = "d510b25e-23c4-4e89-82e2-6fe30e855f6f"
name      = "atan"
namespace = "Maths"
description = "Computes the inverse tangent function of a value to give an angle in radians."
readme    = "README.md"
keywords  = ["arctangent", "trigonometry", "triangle"]

[component.files]
main = "atan.py"

[component.settings]
rad_or_deg_or_grad = { label="Angle Format" }

[component.inports]
value = { name="Value", description="" }

[component.outports]
result = { name="Result", description="" }
