[component]
file = "atan.py"
id = "d510b25e-23c4-4e89-82e2-6fe30e855f6f"

[component.details]
name = "atan"
namespace = "Maths"
description = "Computes the inverse tangent function of a value to give an angle in radians."
keywords = [ "arctangent", "trigonometry", "triangle" ]

[component.details.inports]
value = { name = "Value", description = "" }

[component.details.outports]
result = { name = "Result", description = "" }
