[component]
file = "subtract.py"
id = "b63b0eb2-11c7-4fbd-9317-f2a96e249bde"

[component.details]
name = "Subtract"
namespace = "Maths"
description = "Subtracts the first value from the second value."
keywords = [ "-", "subtraction", "arithmetic", "minus" ]

[component.details.inports]
value1 = { name = "Value 1", description = "" }
value2 = { name = "Value 2", description = "" }

[component.details.outports]
result = { name = "Result", description = "" }
