[component]
id        = "ac1f5353-736e-465e-b7ee-9d3fb7e106ce"
name      = "Round Nearest"
namespace = "Maths"
description = "Outputs the nearest number given the specified number of decimal places."
readme    = "README.md"
keywords  = ["nearest"]

[component.files]
main = "round_nearest.py"

[component.inports]
value        = { name="Value", description="" }
decimal_places = { name="Decimal Places", description="If not given, output will be rounded to nearest integer." }

[component.outports]
result = { name="Result", description="" }
