[component]
file = "round_nearest.py"
id = "ac1f5353-736e-465e-b7ee-9d3fb7e106ce"

[component.details]
name = "Round Nearest"
namespace = "Maths"
description = "Outputs the nearest number given the specified number of decimal places."
readme = "README.md"
keywords = [ "nearest" ]

[component.details.inports]
value = { name = "Value", description = "" }
decimal_places = { name = "Decimal Places", description = "If not given, output will be rounded to nearest integer." }

[component.details.outports]
result = { name = "Result", description = "" }
