[component]
id = "4d39c4bf-6584-4b34-afa5-0ef5e1d783a1"
name = "Range"
namespace = "Maths"
description = "Computes the difference between the largest and smallest number in a collection of values."
keywords = [ "difference", "statistics" ]

[component.files]
main = "range.py"
readme = "README.md"

[component.inports]
values = { name = "Values", description = "A list of values." }

[component.outports]
result = { name = "Result", description = "The range value in the list." }
