[component]
id        = "e1aff00a-e709-4503-9658-78f9182fcc2f"
name      = "Round"
namespace = "Maths"
description = "Rounds up, down, or to the nearest specified number of decimal places."
readme    = "README.md"
keywords  = ["nearest"]

[component.files]
main = "round.py"

[component.settings]
round_type = { label="Round Type" }

[component.inports]
value        = { name="Value", description="" }
decimal_places = { name="Decimal Places", description="If not given, output will be rounded to nearest integer." }

[component.outports]
result = { name="Result", description="" }
