[component]
id        = "57f9e0c1-62d9-492e-b6aa-73e7d93be1bf"
name      = "tan"
namespace = "Maths"
description = "Computes the tangent of an angle which is equal to the opposite length of a right angled triangle divided by its adjacent length."
readme    = "README.md"
keywords  = ["sine", "trigonometry", "triangle"]

[component.files]
main = "tan.py"

[component.settings]
rad_or_deg_or_grad = { label="Angle Format" }

[component.inports]
angle = { name="Angle", description="Angle input." }

[component.outports]
result = { name="Result", description="Outputs a value in a domain of -1 to 1." }
