[component]
file = "tan.py"
id = "57f9e0c1-62d9-492e-b6aa-73e7d93be1bf"

[component.details]
name = "tan"
namespace = "Maths"
description = "Computes the tangent of an angle which is equal to the opposite length of a right angled triangle divided by its hypotenuse length."
keywords = [ "sine", "trigonometry", "triangle" ]

[component.details.inports]
angle = { name = "Angle", description = "Angle in radians." }

[component.details.outports]
result = { name = "Result", description = "" }
