[component]
file = "root.py"
id = "15fd71bf-b61e-4b13-a127-1d13f3dd3f48"

[component.details]
name = "Root"
namespace = "Maths"
description = "Computes the root of a value."
keywords = [ "sqrt", "square root", "^1/2", "cube root" ]

[component.details.inports]
value = { name = "Value", description = "" }
exponent = { name = "Root", description = "" }

[component.details.outports]
result = { name = "Result", description = "" }
