[component]
id        = "15fd71bf-b61e-4b13-a127-1d13f3dd3f48"
name      = "Root"
namespace = "Maths"
description = "Computes the nth root of a value."
readme    = "README.md"
keywords  = ["sqrt", "square root", "^1/2", "cube root"]

[component.files]
main = "root.py"

[component.inports]
value = { name="Value", description="Complex numbers are not yet supported so the root of a negative value will be invalid." }
root = { name="Root", description="Root or radix value. Default value is 2 which gives a square root." }

[component.outports]
result = { name="Result", description="" }
