[component]
id          = "50fea825-f592-40df-a2e5-cdfa1350ae8c"
name        = "Multiply"
namespace   = "Maths"
description = "Multiplies two values together."
keywords    = ["*", "multiplication", "arithmetic", "product", "times"]

[component.files]
main   = "multiply.py"
readme = "README.md"

[component.settings]
terms = { label = "Number of Terms" }

[component.inports]
value1 = { name = "Value 1", description = "First value to be multiplied." }
value2 = { name = "Value 2", description = "Second value to be multiplied." }

[component.outports]
result = { name = "Result", description = "Result of the multiplication." }
