[component]
file = "multiply.py"
id = "50fea825-f592-40df-a2e5-cdfa1350ae8c"

[component.details]
name = "Multiply"
namespace = "Maths"
description = "Multiplies two values together."
keywords = [ "*", "multiplication", "arithmetic", "product", "times" ]

[component.details.inports]
value1 = { name = "Value 1", description = "" }
value2 = { name = "Value 2", description = "" }

[component.details.outports]
result = { name = "Result", description = "" }
