[component]
id = "50fea825-f592-40df-a2e5-cdfa1350ae8c"
name = "Multiply"
namespace = "Maths"
description = "Multiplies two values together."
keywords = [ "*", "multiplication", "arithmetic", "product", "times" ]

[component.files]
main = "multiply.py"
readme = "README.md"

[component.outports]
result = { name = "Result", description = "" }

[component.settings]
terms = { label = "Number of Terms" }
