name: GitFlow
# This workflow makes sure that when the master branch is updated and a new
# release is made, a PR is made to the develop branch to keep it up to date.
# This is the convention GitFlow specifies

# Trigger the workflow on stable release from master
# branch by the semantic-release automation
on:
  release:
    types:
      - released

jobs:
  create-pr:
    name: Create PR to Develop Branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Create PR to Develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.TEC_DEVBOT_ACCESS_TOKEN }}
